version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - npm install @vscode/sqlite3 --build-from-source --no-save
      - npm install
  build:
    commands:
      - npm test
      - echo //registry.npmjs.org/:_authToken=${NPM_TOKEN} > .npmrc
      - npm publish $PUBLISH_ARGS --unsafe-perm
